In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv("student_scores.csv") 
df.head()

,student_id,name,age,gender,math_score,science_score,attendance,exam_date
0,1,Teresa,NaN,Female,NaN,NaN,NaN,NaN
1,2,Amber,20,Female,NaN,70.0,65.0,NaN
2,3,Sherri,18,Female,150.0,70.0,65.0,March 5 2024
3,4,Brittany,twenty,Male,150.0,NaN,90.0,NaN
4,5,Daniel,18,Female,NaN,999.0,72.0,2024-03-12

In [ ]:
# creating numpy array and performing it's operations

import numpy as np

math_scores = df['math_score'].values
math_array = np.array(math_scores)

In [4]:
mean = np.mean(math_array)
median = np.median(math_array)
maximum = np.max(math_array)
minimum = np.min(math_array)

print(mean, median, maximum, minimum)

nan nan nan nan

In [6]:
normalized_scores = (math_array - minimum) / (maximum - minimum)
print(normalized_scores)

[nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan nan
 nan nan nan nan nan nan nan nan nan nan nan nan nan nan]

In [ ]:
# pandas exploration

import pandas as pd

df = pd.read_csv("student_scores.csv")

In [10]:
df.head()

,student_id,name,age,gender,math_score,science_score,attendance,exam_date
0,1,Teresa,NaN,Female,NaN,NaN,NaN,NaN
1,2,Amber,20,Female,NaN,70.0,65.0,NaN
2,3,Sherri,18,Female,150.0,70.0,65.0,March 5 2024
3,4,Brittany,twenty,Male,150.0,NaN,90.0,NaN
4,5,Daniel,18,Female,NaN,999.0,72.0,2024-03-12

In [12]:
df.dtypes

student_id         int64
name                 str
age                  str
gender               str
math_score       float64
science_score    float64
attendance       float64
exam_date            str
dtype: object

In [14]:
df.isnull().sum()

student_id        0
name              0
age               5
gender            8
math_score        6
science_score     5
attendance       11
exam_date         9
dtype: int64

In [16]:
low_attendance = df[df['attendance'] < 70]
print(low_attendance)

    student_id       name  age  gender  math_score  science_score  attendance  \
1            2      Amber   20  Female         NaN           70.0        65.0
2            3     Sherri   18  Female       150.0           70.0        65.0
5            6  Frederick   21  Female         NaN          999.0        65.0
11          12       Luis  NaN    Male        55.0           60.0        65.0
20          21      Amber   21  Female        67.0            NaN        65.0
22          23     Ronald   20     NaN        67.0          999.0        65.0
28          29  Elizabeth  NaN  Female        91.0           70.0        65.0
30           6  Frederick   21  Female         NaN          999.0        65.0

       exam_date
1            NaN
2   March 5 2024
5     12-03-2024
11  March 5 2024
20    12-03-2024
22  March 5 2024
28           NaN
30    12-03-2024

In [ ]:
# data preprocessing
df.fillna(df.mean(numeric_only=True), inplace=True)

,student_id,name,age,gender,math_score,science_score,attendance,exam_date
0,1,Teresa,NaN,Female,91.346154,453.296296,74.285714,NaN
1,2,Amber,20,Female,91.346154,70.000000,65.000000,NaN
2,3,Sherri,18,Female,150.000000,70.000000,65.000000,March 5 2024
3,4,Brittany,twenty,Male,150.000000,453.296296,90.000000,NaN
4,5,Daniel,18,Female,91.346154,999.000000,72.000000,2024-03-12
5,6,Frederick,21,Female,91.346154,999.000000,65.000000,12-03-2024
6,7,Eric,twenty,Male,55.000000,999.000000,80.000000,2024-03-12
7,8,Carolyn,NaN,Female,88.000000,999.000000,74.285714,2024-03-12
8,9,Frank,18,Female,150.000000,60.000000,74.285714,12-03-2024
9,10,James,18,Male,55.000000,95.000000,74.285714,12-03-2024
10,11,John,21,NaN,72.000000,70.000000,74.285714,NaN
11,12,Luis,NaN,Male,55.000000,60.000000,65.000000,March 5 2024
12,13,Angela,18,Male,91.000000,999.000000,72.000000,12-03-2024
13,14,Allison,21,Female,67.000000,85.000000,80.000000,12-03-2024
14,15,Donald,twenty,Female,88.000000,999.000000,74.285714,12-03-2024
15,16,Kathleen,19,NaN,67.000000,95.000000,72.000000,12-03-2024
16,17,Rebecca,twenty,Male,150.000000,453.296296,74.285714,12-03-2024
17,18,Sarah,21,NaN,150.000000,60.000000,90.000000,2024-03-12
18,19,Jennifer,21,NaN,88.000000,95.000000,90.000000,March 5 2024
19,20,John,NaN,Male,91.346154,85.000000,72.000000,2024-03-12
20,21,Amber,21,Female,67.000000,453.296296,65.000000,12-03-2024
21,22,James,21,Male,67.000000,453.296296,74.285714,2024-03-12
22,23,Ronald,20,NaN,67.000000,999.000000,65.000000,March 5 2024
23,24,Evan,18,NaN,67.000000,999.000000,74.285714,2024-03-12
24,25,Douglas,twenty,Female,91.000000,85.000000,80.000000,NaN
25,26,Michael,twenty,NaN,88.000000,999.000000,74.285714,NaN
26,27,Kimberly,21,Female,150.000000,95.000000,90.000000,NaN
27,28,Brittany,18,Male,67.000000,999.000000,72.000000,March 5 2024
28,29,Elizabeth,NaN,Female,91.000000,70.000000,65.000000,NaN
29,30,Janice,19,Male,72.000000,85.000000,80.000000,2024-03-12
30,6,Frederick,21,Female,91.346154,999.000000,65.000000,12-03-2024
31,11,John,21,NaN,72.000000,70.000000,74.285714,NaN

In [20]:
df.dropna(inplace=True)

In [22]:
df['math_score'] = df['math_score'].astype(float)

In [27]:
df['exam_date'] = pd.to_datetime(df['exam_date'], errors='coerce')

In [29]:
Q1 = df['math_score'].quantile(0.25)
Q3 = df['math_score'].quantile(0.75)
IQR = Q3 - Q1

df = df[(df['math_score'] >= Q1 - 1.5*IQR) & 
        (df['math_score'] <= Q3 + 1.5*IQR)]

In [31]:
df.drop_duplicates(inplace=True)

In [38]:
# data analysis
df['average_score'] = (df['math_score'] + df['science_score']) / 2
top5 = df.sort_values(by='average_score', ascending=False).head(5)
print(top5)

    student_id       name     age  gender  math_score  science_score  \
4            5     Daniel      18  Female   91.346154          999.0
5            6  Frederick      21  Female   91.346154          999.0
12          13     Angela      18    Male   91.000000          999.0
14          15     Donald  twenty  Female   88.000000          999.0
27          28   Brittany      18    Male   67.000000          999.0

    attendance  exam_date  average_score
4    72.000000        NaT     545.173077
5    65.000000        NaT     545.173077
12   72.000000        NaT     545.000000
14   74.285714        NaT     543.500000
27   72.000000 2024-03-05     533.000000

In [36]:
correlation = df['attendance'].corr(df['average_score'])
print(correlation)

-0.38001272017332377

In [37]:
grouped = df.groupby('gender')['average_score'].mean()
print(grouped)

gender
Female    393.998860
Male      336.441358
Name: average_score, dtype: float64